let
    Source = Csv.Document(File.Contents("C:\Users\abula\OneDrive\Desktop\excel\CF-CA-equities-01-01-2019-to-31-12-2023.csv"),[Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SYMBOL", type text}, {"COMPANY NAME", type text}, {"SERIES", type text}, {"PURPOSE", type text}, {"FACE VALUE", Int64.Type}, {"EX-DATE", type date}, {"RECORD DATE", type text}, {"BOOK CLOSURE START DATE", type text}, {"BOOK CLOSURE END DATE", type text}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"RECORD DATE", "BOOK CLOSURE START DATE", "BOOK CLOSURE END DATE", "FACE VALUE"}),
    #"Filtered Rows" = Table.SelectRows(#"Removed Columns", each ([SERIES] = "EQ")),
    #"Added Custom" = Table.AddColumn(#"Filtered Rows", "ACTION", each if Text.Contains([PURPOSE], "Dividend") then "Dividend" else if Text.Contains([PURPOSE], "Buy Back") then "Buy Back" else if Text.Contains([PURPOSE], "Split") then "Split" else if Text.Contains([PURPOSE], "Bonus") then "Bonus Share" else if Text.Contains([PURPOSE], "Final Dividend") then "Final Dividend" else "Other"),
    #"Filtered Rows1" = Table.SelectRows(#"Added Custom", each ([ACTION] <> "Other")),
    #"Changed Type1" = Table.TransformColumnTypes(#"Filtered Rows1",{{"ACTION", type text}}),
    #"Inserted Text Between Delimiters" = Table.AddColumn(#"Changed Type1", "Text Between Delimiters", each Text.BetweenDelimiters([PURPOSE], "-", "Per"), type text),
    #"Renamed Columns" = Table.RenameColumns(#"Inserted Text Between Delimiters",{{"Text Between Delimiters", "dividend per share"}}),
    #"Inserted Text After Delimiter" = Table.AddColumn(#"Renamed Columns", "Text After Delimiter", each Text.AfterDelimiter([dividend per share], "Rs"), type text),
    #"Inserted Text After Delimiter1" = Table.AddColumn(#"Inserted Text After Delimiter", "Text After Delimiter.1", each Text.AfterDelimiter([dividend per share], "Re"), type text),
    #"Inserted Merged Column" = Table.AddColumn(#"Inserted Text After Delimiter1", "Diviednd per share", each Text.Combine({[Text After Delimiter], [Text After Delimiter.1]}, ""), type text),
    #"Removed Columns1" = Table.RemoveColumns(#"Inserted Merged Column",{"Text After Delimiter", "Text After Delimiter.1"}),
    #"Filtered Rows2" = Table.SelectRows(#"Removed Columns1", each ([Diviednd per share] <> " 4 Share")),
    #"Replaced Value" = Table.ReplaceValue(#"Filtered Rows2","/-"," ",Replacer.ReplaceText,{"Diviednd per share"}),
    #"Filtered Rows3" = Table.SelectRows(#"Replaced Value", each ([PURPOSE] <> " Scheme Of Arangement- Bonus - 1 Debenture For 1 Equity Share Held" and [PURPOSE] <> "Bonus Ncrps 1:116" and [PURPOSE] <> "Scheme Of Arrangement - Bonus Ncrps 1:10")),
    #"Removed Columns2" = Table.RemoveColumns(#"Filtered Rows3",{"dividend per share"}),
    #"Filtered Rows4" = Table.SelectRows(#"Removed Columns2", each true),
    #"Added Custom1" = Table.AddColumn(#"Filtered Rows4", "Custom", each Text.SplitAny([PURPOSE], {"Re ", "Rs "})),
    #"Removed Columns3" = Table.RemoveColumns(#"Added Custom1",{"Custom"}),
    #"Inserted Text After Delimiter2" = Table.AddColumn(#"Removed Columns3", "Text After Delimiter", each Text.AfterDelimiter([PURPOSE], "Face Value Split (Sub-Division) - From Rs "), type text),
    #"Filtered Rows5" = Table.SelectRows(#"Inserted Text After Delimiter2", each true),
    #"Inserted Text Before Delimiter" = Table.AddColumn(#"Filtered Rows5", "Text Before Delimiter", each Text.BeforeDelimiter([Text After Delimiter], "To"), type text),
    #"Inserted Text After Delimiter3" = Table.AddColumn(#"Inserted Text Before Delimiter", "Text After Delimiter.1", each Text.AfterDelimiter([Text After Delimiter], "To"), type text),
    #"Replaced Value1" = Table.ReplaceValue(#"Inserted Text After Delimiter3","/- Per Share "," ",Replacer.ReplaceText,{"Text Before Delimiter"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Per Share "," ",Replacer.ReplaceText,{"Text Before Delimiter"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","/- Per Share"," ",Replacer.ReplaceText,{"Text After Delimiter.1"}),
    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","Rs","",Replacer.ReplaceText,{"Text After Delimiter.1"}),
    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","Per Share","",Replacer.ReplaceText,{"Text After Delimiter.1"}),
    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","Re"," ",Replacer.ReplaceText,{"Text After Delimiter.1"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Replaced Value6",{{"Text Before Delimiter", type number}, {"Text After Delimiter.1", type number}}),
    #"Merged Columns" = Table.CombineColumns(Table.TransformColumnTypes(#"Changed Type2", {{"Text Before Delimiter", type text}, {"Text After Delimiter.1", type text}}, "en-IN"),{"Text Before Delimiter", "Text After Delimiter.1"},Combiner.CombineTextByDelimiter(":", QuoteStyle.None),"stock split ratio"),
    #"Replaced Value7" = Table.ReplaceValue(#"Merged Columns",":"," ",Replacer.ReplaceValue,{"stock split ratio"}),
    #"Removed Columns4" = Table.RemoveColumns(#"Replaced Value7",{"Text After Delimiter"}),
    #"Replaced Value8" = Table.ReplaceValue(#"Removed Columns4"," ","-",Replacer.ReplaceText,{"stock split ratio"}),
    #"Added Conditional Column" = Table.AddColumn(#"Replaced Value8", "Custom", each if Text.Contains([stock split ratio], "-") then [Diviednd per share] else " "),
    #"Filtered Rows6" = Table.SelectRows(#"Added Conditional Column", each true),
    #"Renamed Columns1" = Table.RenameColumns(#"Filtered Rows6",{{"Custom", "dividend per share"}}),
    #"Removed Columns5" = Table.RemoveColumns(#"Renamed Columns1",{"Diviednd per share"}),
    #"Replaced Value9" = Table.ReplaceValue(#"Removed Columns5","-"," ",Replacer.ReplaceText,{"stock split ratio"}),
    #"Inserted Merged Column1" = Table.AddColumn(#"Replaced Value9", "Merged", each Text.Combine({[ACTION], [stock split ratio], [dividend per share]}, " "), type text),
    #"Removed Columns6" = Table.RemoveColumns(#"Inserted Merged Column1",{"dividend per share", "stock split ratio"}),
    #"Added Conditional Column1" = Table.AddColumn(#"Removed Columns6", "Custom", each if Text.Contains([Merged], "Dividend ") then "per share" else null),
    #"Merged Columns1" = Table.CombineColumns(#"Added Conditional Column1",{"Merged", "Custom"},Combiner.CombineTextByDelimiter(" ", QuoteStyle.None),"Merged.1"),
    #"Filtered Rows8" = Table.SelectRows(#"Merged Columns1", each true),
    #"Added Conditional Column2" = Table.AddColumn(#"Filtered Rows8", "BONUS", each if Text.Contains([PURPOSE], "Bonus") then [PURPOSE] else null),
    #"Added Conditional Column3" = Table.AddColumn(#"Added Conditional Column2", "Custom", each if Text.Contains([Merged.1], "Bonus Share") then [BONUS] else [Merged.1]),
    #"Removed Columns7" = Table.RemoveColumns(#"Added Conditional Column3",{"Merged.1", "BONUS"}),
    #"Replaced Value10" = Table.ReplaceValue(#"Removed Columns7","Share"," ",Replacer.ReplaceText,{"ACTION"}),
    #"Filtered Rows7" = Table.SelectRows(#"Replaced Value10", each true),
    #"Renamed Columns2" = Table.RenameColumns(#"Filtered Rows7",{{"Custom", "NOTE"}}),
    #"Removed Columns8" = Table.RemoveColumns(#"Renamed Columns2",{"PURPOSE"}),
    #"Inserted Text Between Delimiters1" = Table.AddColumn(#"Removed Columns8", "Text Between Delimiters", each Text.BetweenDelimiters([NOTE], "Dividend", "per"), type text),
    #"Inserted Text After Delimiter4" = Table.AddColumn(#"Inserted Text Between Delimiters1", "Text After Delimiter", each Text.AfterDelimiter([NOTE], "Split"), type text),
    #"Inserted Text After Delimiter5" = Table.AddColumn(#"Inserted Text After Delimiter4", "Text After Delimiter.1", each Text.AfterDelimiter([NOTE], "Bonus"), type text),
    #"Merged Columns2" = Table.CombineColumns(#"Inserted Text After Delimiter5",{"Text Between Delimiters", "Text After Delimiter", "Text After Delimiter.1"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"METRICS"),
    #"Added Conditional Column4" = Table.AddColumn(#"Merged Columns2", "DIVIDEND PER SHARE", each if [METRICS] <> ":" then [METRICS] else null),
    #"Changed Type3" = Table.TransformColumnTypes(#"Added Conditional Column4",{{"DIVIDEND PER SHARE", type number}}),
    #"Replaced Errors" = Table.ReplaceErrorValues(#"Changed Type3", {{"DIVIDEND PER SHARE", null}}),
    #"Added Conditional Column5" = Table.AddColumn(#"Replaced Errors", "RATIO (SPLIT/BONUS)", each if [DIVIDEND PER SHARE] = null then [METRICS] else null),
    #"Removed Columns9" = Table.RemoveColumns(#"Added Conditional Column5",{"METRICS"}),
    #"Replaced Value11" = Table.ReplaceValue(#"Removed Columns9",null,"",Replacer.ReplaceValue,{"RATIO (SPLIT/BONUS)"}),
    #"Changed Type4" = Table.TransformColumnTypes(#"Replaced Value11",{{"RATIO (SPLIT/BONUS)", type text}})
in
    #"Changed Type4"